services:
  postgres:
    image: postgres:16
    container_name: pg16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tagtrek
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

#  springboot:
#    build: .
#    container_name: tagtrek-api
#    depends_on:
#      - postgres
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tagtrek
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#    ports:
#      - "8080:8080"

volumes:
  pgdata:
