spring:
  application:
    name: tag-trek
#  datasource:
#    url: jdbc:postgresql://localhost:5432/tagtrek
#    username: postgres
#    password: postgres
#  jpa:
#    hibernate:
#      ddl-auto: update